In [2]:
import re
import os 
from pathlib import Path

import pandas as pd
curr_dir = Path.cwd()
DATA_DIR = curr_dir.parent / "data"

In [5]:
geo_loc = pd.read_csv(DATA_DIR / "geocoded_addresses.csv")

In [6]:
list(geo_loc.loc[geo_loc["onemap_searchval"].isna()]["address"])

['1 JLN PASAR BARU',
 '1 REDHILL CL',
 '10 GHIM MOH RD',
 '10 TEBAN GDNS RD',
 '10 UPP BOON KENG RD',
 '10 YUNG KUANG RD',
 '107 DEPOT RD',
 '11 REDHILL CL',
 '11 SHORT ST',
 '110 BT MERAH VIEW',
 '111 BT MERAH VIEW',
 '113 BT MERAH VIEW',
 '114 BT MERAH VIEW',
 '12 REDHILL CL',
 '12 SHORT ST',
 '13 REDHILL CL',
 '13 SHORT ST',
 '13 TEBAN GDNS RD',
 '137 ALEXANDRA RD',
 '14 TEBAN GDNS RD',
 '142 HU CHING RD',
 '142 TIONG BAHRU RD',
 '145 HU CHING RD',
 '16 REDHILL CL',
 '166 LOR 1 TOA PAYOH',
 '167 BOON LAY DR',
 '167 LOR 1 TOA PAYOH',
 '168 BOON LAY DR',
 '169 BOON LAY DR',
 '17 REDHILL CL',
 '170 BOON LAY DR',
 '171 BOON LAY DR',
 '172 BOON LAY DR',
 '172 STIRLING RD',
 '173 STIRLING RD',
 '18 KG BAHRU HILL',
 '18 REDHILL CL',
 '19 KG BAHRU HILL',
 '19 REDHILL CL',
 '1A WOODLANDS CTR RD',
 '2 EAST COAST RD',
 '2 REDHILL CL',
 '20 REDHILL CL',
 '20 UPP BOON KENG RD',
 '21 OUTRAM PK',
 '21 REDHILL CL',
 '22 KG BAHRU HILL',
 '22 OUTRAM PK',
 '22 REDHILL CL',
 '220 BOON LAY AVE',
 '23 KG BAHRU HILL',
 '24 DOVER CRES',
 '24 JLN MEMBINA BARAT',
 '24 KG BAHRU HILL',
 '24 TANGLIN HALT RD',
 '247 ANG MO KIO AVE 3',
 '248 ANG MO KIO AVE 2',
 '25 TANGLIN HALT RD',
 '252 ANG MO KIO AVE 4',
 '26 TANGLIN HALT RD',
 '27 TANGLIN HALT RD',
 "27A C'WEALTH AVE",
 '28 TANGLIN HALT RD',
 '29 HAVELOCK RD',
 '29 TANGLIN HALT RD',
 '2A WOODLANDS CTR RD',
 '3 EAST COAST RD',
 '3 LIM CHU KANG RD',
 '3 REDHILL CL',
 '3 ROCHOR RD',
 '3 TEBAN GDNS RD',
 '30 LOR 5 TOA PAYOH',
 '31 DOVER RD',
 '31 TAMAN HO SWEE',
 '31 TANGLIN HALT RD',
 '313 CLEMENTI AVE 4',
 '314 CLEMENTI AVE 4',
 '316 ANG MO KIO AVE 1',
 '32 LOWER DELTA RD',
 '32 TANGLIN HALT RD',
 '322 CLEMENTI AVE 5',
 '323 CLEMENTI AVE 5',
 '33 TAMAN HO SWEE',
 '35 DOVER RD',
 '36 DOVER RD',
 '38 DOVER RD',
 "39A C'WEALTH AVE",
 '4 HILLVIEW AVE',
 '4 ROCHOR RD',
 '401 CLEMENTI AVE 1',
 '402 CLEMENTI AVE 1',
 '403 CLEMENTI AVE 1',
 '407 CLEMENTI AVE 1',
 '409 CLEMENTI AVE 1',
 '45 TANGLIN HALT RD',
 '454 ANG MO KIO AVE 10',
 '455 ANG MO KIO AVE 10',
 '5 BUANGKOK STH FARMWAY 1',
 '5 REDHILL CL',
 '5 TEBAN GDNS RD',
 '5 YUNG PING RD',
 '51 NILE RD',
 '51 TANGLIN HALT RD',
 '52 TANGLIN HALT RD',
 '53 TANGLIN HALT RD',
 '54 NILE RD',
 '54 SIMS DR',
 '54 TANGLIN HALT RD',
 '59 SIMS DR',
 '6 HILLVIEW AVE',
 '6 REDHILL CL',
 '6 TEBAN GDNS RD',
 '6 UPP BOON KENG RD',
 '6 YUNG PING RD',
 '62 SIMS DR',
 '68 DAKOTA CRES',
 '7 HILLVIEW AVE',
 '7 REDHILL CL',
 '7 TEBAN GDNS RD',
 '7 YUNG KUANG RD',
 "76 C'WEALTH DR",
 "77 C'WEALTH DR",
 "78 C'WEALTH DR",
 "79 C'WEALTH DR",
 '8 HILLVIEW AVE',
 '8 REDHILL CL',
 '8 YUNG KUANG RD',
 "80 C'WEALTH DR",
 '83 BEDOK NTH RD',
 '88 ZION RD',
 '89 LOR 2 TOA PAYOH',
 '89 ZION RD',
 '9 REDHILL CL',
 '90 ZION RD',
 '91 ZION RD',
 '96 MARGARET DR']

In [7]:
ONEMAP_SEARCH_URL = "https://www.onemap.gov.sg/api/common/elastic/search"
from dotenv import load_dotenv

load_dotenv()
import os 
token = os.environ.get("ONEMAP_TOKEN")

## Found 5 Jln Batu wrongly mapped to bus depot

In [9]:
import requests
response = requests.get(
    ONEMAP_SEARCH_URL, 
    params = {"searchVal":"5 Jln Batu", "returnGeom": "Y", "getAddrDetails": "Y", "pageNum": 1,},
    headers= {"Authorization": token},
    timeout=60
)   
response
response.json()

{'found': 3,
 'totalNumPages': 1,
 'pageNum': 1,
 'results': [{'SEARCHVAL': 'BUS DEPOT BUILDING',
   'BLK_NO': '5',
   'ROAD_NAME': 'JALAN GALI BATU',
   'BUILDING': 'BUS DEPOT BUILDING',
   'ADDRESS': '5 JALAN GALI BATU BUS DEPOT BUILDING SINGAPORE 679530',
   'POSTAL': '679530',
   'X': '19536.4256569259',
   'Y': '41493.4725335278',
   'LATITUDE': '1.39152550534761',
   'LONGITUDE': '103.757266741055'},
  {'SEARCHVAL': 'DI TANJONG RHU',
   'BLK_NO': '5',
   'ROAD_NAME': 'JALAN BATU',
   'BUILDING': 'DI TANJONG RHU',
   'ADDRESS': '5 JALAN BATU DI TANJONG RHU SINGAPORE 431005',
   'POSTAL': '431005',
   'X': '33643.5536485799',
   'Y': '31545.8646950517',
   'LATITUDE': '1.30156359677462',
   'LONGITUDE': '103.884028473673'},
  {'SEARCHVAL': 'HOCK SENG PARK',
   'BLK_NO': '5',
   'ROAD_NAME': 'JALAN JAMBU BATU',
   'BUILDING': 'HOCK SENG PARK',
   'ADDRESS': '5 JALAN JAMBU BATU HOCK SENG PARK SINGAPORE 588724',
   'POSTAL': '588724',
   'X': '22947.5189414099',
   'Y': '35319.6594705638',
   'LATITUDE': '1.33569255382966',
   'LONGITUDE': '103.787919120925'}]}

In [12]:
geo_loc.loc[geo_loc["address"] == "5 JLN BATU"]

,address,onemap_searchval,onemap_blk_no,onemap_road_name,onemap_building,onemap_address,onemap_postal,onemap_x,onemap_y,latitude,longitude
6291,5 JLN BATU,BUS DEPOT BUILDING,5,JALAN GALI BATU,BUS DEPOT BUILDING,5 JALAN GALI BATU BUS DEPOT BUILDING SINGAPORE...,679530,19536.42566,41493.47253,1.391526,103.757267

In [15]:
dic = response.json()["results"][1]

In [16]:
dic

{'SEARCHVAL': 'DI TANJONG RHU',
 'BLK_NO': '5',
 'ROAD_NAME': 'JALAN BATU',
 'BUILDING': 'DI TANJONG RHU',
 'ADDRESS': '5 JALAN BATU DI TANJONG RHU SINGAPORE 431005',
 'POSTAL': '431005',
 'X': '33643.5536485799',
 'Y': '31545.8646950517',
 'LATITUDE': '1.30156359677462',
 'LONGITUDE': '103.884028473673'}

In [18]:
update_lst = {
    "onemap_searchval": dic.get("SEARCHVAL"),
    "onemap_blk_no": dic.get("BLK_NO"),
    "onemap_road_name": dic.get("ROAD_NAME"),
    "onemap_building": dic.get("BUILDING"),
    "onemap_address": dic.get("ADDRESS"),
    "onemap_postal": dic.get("POSTAL"),
    "onemap_x": float(dic["X"]) if dic.get("X") else None,
    "onemap_y": float(dic["Y"]) if dic.get("Y") else None,
    "latitude": float(dic["LATITUDE"]),
    "longitude": float(dic["LONGITUDE"]),
}

In [19]:
geo_loc.loc[geo_loc["address"] == "5 JLN BATU", list(update_lst.keys())] = list(update_lst.values())

In [25]:
geo_loc.to_csv(DATA_DIR / "geocoded_addresses.csv")

In [7]:
test = response.json()
test['results'][2]

{'SEARCHVAL': 'HOCK SENG PARK',
 'BLK_NO': '5',
 'ROAD_NAME': 'JALAN JAMBU BATU',
 'BUILDING': 'HOCK SENG PARK',
 'ADDRESS': '5 JALAN JAMBU BATU HOCK SENG PARK SINGAPORE 588724',
 'POSTAL': '588724',
 'X': '22947.5189414099',
 'Y': '35319.6594705638',
 'LATITUDE': '1.33569255382966',
 'LONGITUDE': '103.787919120925'}

In [40]:
df_total = pd.read_csv(DATA_DIR / "merged_resale_prices.csv")

In [41]:
len(df_total)

981352

In [42]:
df_total.town.unique()

array(['ANG MO KIO', 'BEDOK', 'BISHAN', 'BUKIT BATOK', 'BUKIT MERAH',
       'BUKIT TIMAH', 'CENTRAL AREA', 'CHOA CHU KANG', 'CLEMENTI',
       'GEYLANG', 'HOUGANG', 'JURONG EAST', 'JURONG WEST',
       'KALLANG/WHAMPOA', 'MARINE PARADE', 'QUEENSTOWN', 'SENGKANG',
       'SERANGOON', 'TAMPINES', 'TOA PAYOH', 'WOODLANDS', 'YISHUN',
       'LIM CHU KANG', 'SEMBAWANG', 'BUKIT PANJANG', 'PASIR RIS',
       'PUNGGOL'], dtype=object)

## Merge to planning area

Merge to plannign area for different regions

In [35]:
df_planning_area= pd.read_csv(DATA_DIR / "SG_planning_areas.csv")

In [36]:
df_planning_area["town_cleaned"] = df_planning_area.Town.str.upper()
df_planning_area.loc[df_planning_area["Town"] == "Jurong East • Jurong Timur", "town_cleaned"] = "JURONG EAST"
df_planning_area.loc[df_planning_area["Town"] == "Jurong West • Jurong Barat", "town_cleaned"] = "JURONG WEST"
df_planning_area.loc[df_planning_area["Town"] == "Kallang", "town_cleaned"] = "KALLANG/WHAMPOA"

In [37]:
import numpy as np

In [38]:
df_planning_area.loc[len(df_planning_area)] = ["Central Area", "Central", 17.84, np.nan, np.nan, np.nan, "CENTRAL AREA"]

In [39]:
df_planning_area

,Town,Region,Area (km2),Population (2025)[8],Population density (/km2),Subzones,town_cleaned
0,Ang Mo Kio,North-East,13.94,"158,720","11,386",12.0,ANG MO KIO
1,Bedok,East,21.69,"274,360","12,649",8.0,BEDOK
2,Bishan,Central,7.62,"87,530","11,487",3.0,BISHAN
3,Boon Lay,West,8.23,30,4,4.0,BOON LAY
4,Bukit Batok,West,11.13,"165,830","14,899",9.0,BUKIT BATOK
5,Bukit Merah,Central,14.34,"146,200","10,195",17.0,BUKIT MERAH
6,Bukit Panjang,West,8.99,"136,360","15,168",7.0,BUKIT PANJANG
7,Bukit Timah,Central,17.53,"85,900","4,900",8.0,BUKIT TIMAH
8,Central Water Catchment • Kawasan Tadahan Air ...,North,37.15,–,–,NaN,CENTRAL WATER CATCHMENT • KAWASAN TADAHAN AIR ...
9,Changi,East,40.61,"1,960",48,3.0,CHANGI
10,Changi Bay • Teluk Changi,East,1.70,–,–,NaN,CHANGI BAY • TELUK CHANGI
11,Choa Chu Kang,West,6.11,"187,550","30,696",6.0,CHOA CHU KANG
12,Clementi,West,9.49,"104,240","10,984",9.0,CLEMENTI
13,Downtown Core • Pusat Bandar,Central,4.34,"5,230","1,205",13.0,DOWNTOWN CORE • PUSAT BANDAR
14,Geylang,Central,9.64,"117,640","12,203",5.0,GEYLANG
15,Hougang,North-East,13.93,"227,220","16,312",10.0,HOUGANG
16,Jurong East • Jurong Timur,West,17.83,"72,950","4,091",11.0,JURONG EAST
17,Jurong West • Jurong Barat,West,14.69,"253,840","17,280",9.0,JURONG WEST
18,Kallang,Central,9.17,"101,720","11,093",9.0,KALLANG/WHAMPOA
19,Lim Chu Kang,North,17.30,30,2,NaN,LIM CHU KANG
20,Mandai,North,11.77,"2,120",180,3.0,MANDAI
21,Marina East • Marina Timur,Central,1.82,–,–,NaN,MARINA EAST • MARINA TIMUR
22,Marina South • Marina Selatan,Central,1.62,–,–,NaN,MARINA SOUTH • MARINA SELATAN
23,Marine Parade,Central,6.12,"47,480","7,758",5.0,MARINE PARADE
24,Museum • Muzium,Central,0.83,820,988,3.0,MUSEUM • MUZIUM
25,Newton,Central,2.07,"10,110","4,884",6.0,NEWTON
26,North-Eastern Islands • Kepulauan Timur Laut,North-East,42.88,40,1,NaN,NORTH-EASTERN ISLANDS • KEPULAUAN TIMUR LAUT
27,Novena,Central,8.98,"53,160","5,920",5.0,NOVENA
28,Orchard,Central,0.96,"1,450","1,510",3.0,ORCHARD
29,Outram,Central,1.37,"16,940","12,365",4.0,OUTRAM
30,Pasir Ris,East,15.02,"144,260","9,605",8.0,PASIR RIS
31,Paya Lebar,East,11.69,20,2,5.0,PAYA LEBAR
32,Pioneer,West,12.10,50,4,5.0,PIONEER
33,Punggol,North-East,9.34,"204,150","21,858",7.0,PUNGGOL
34,Queenstown,Central,20.43,"101,480","4,967",15.0,QUEENSTOWN
35,River Valley,Central,1.48,"12,700","8,581",5.0,RIVER VALLEY
36,Rochor,Central,1.62,"12,790","7,895",10.0,ROCHOR
37,Seletar,North-East,10.25,290,28,4.0,SELETAR
38,Sembawang,North,12.34,"113,350","9,186",9.0,SEMBAWANG
39,Sengkang,North-East,10.59,"267,600","25,269",7.0,SENGKANG
40,Serangoon,North-East,10.10,"116,630","11,548",7.0,SERANGOON
41,Simpang,North,5.13,–,–,4.0,SIMPANG
42,Singapore River • Sungai Singapura,Central,0.96,"4,630","4,823",3.0,SINGAPORE RIVER • SUNGAI SINGAPURA
43,Southern Islands • Kepulauan Selatan,Central,6.07,"2,680",442,2.0,SOUTHERN ISLANDS • KEPULAUAN SELATAN
44,Straits View • Pemandangan Selat,Central,0.77,–,–,NaN,STRAITS VIEW • PEMANDANGAN SELAT
45,Sungei Kadut • Sungai Kadut,North,15.99,730,46,5.0,SUNGEI KADUT • SUNGAI KADUT
46,Tampines,East,20.89,"290,090","13,887",5.0,TAMPINES
47,Tanglin,Central,7.63,"24,630","3,228",4.0,TANGLIN
48,Tengah,West,7.40,"22,960","3,103",6.0,TENGAH
49,Toa Payoh,Central,8.17,"142,220","17,408",12.0,TOA PAYOH
50,Tuas,West,30.04,80,3,6.0,TUAS
51,Western Islands • Kepulauan Barat,West,39.47,10,0,3.0,WESTERN ISLANDS • KEPULAUAN BARAT
52,Western Water Catchment • Kawasan Tadahan Air ...,West,69.46,580,8,3.0,WESTERN WATER CATCHMENT • KAWASAN TADAHAN AIR ...
53,Woodlands,North,13.59,"254,440","18,723",9.0,WOODLANDS
54,Yishun,North,21.24,"228,730","10,769",9.0,YISHUN
55,Central Area,Central,17.84,NaN,NaN,NaN,CENTRAL AREA

In [43]:
df_geo = pd.read_csv(DATA_DIR/ "geocoded_addresses.csv")

In [44]:
df_merge_geo = df_total.merge(df_geo, how="left", on="address")
final_df = df_merge_geo.merge(df_planning_area, how='left', left_on="town", right_on="town_cleaned")

In [46]:
final_df.to_csv(DATA_DIR / "geocode_final.csv",index=False)